/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maven_tabla;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author valde
 */
public class FRAME_Tabla extends javax.swing.JFrame {

    ManejoDeDatos manejador = new ManejoDeDatos();
    File rutaTabla = new File("personas.txt");
    boolean vaciarCampos = true;
    
    /**
     * Creates new form FRAME_Tabla
     */
    public FRAME_Tabla() {
        initComponents();
    }

    //DEVUELVE true SI EL CAMPO ES VACÍO O false SI TIENE ALGO
    public boolean comprobarCampoVacio(JTextField campo){
        return campo.getText().equals("");
    }
    
    public void vaciarCampos(){
        txtFieldNombre.setText("");
        txtFieldApellido1.setText("");
        txtFieldApellido2.setText("");
        txtFieldEdad.setText("");
    }
    
    //-3 = no inicializado
    //-2 = campo edad no es numero
    //-1 = campo sin completar
    // 0 = campos correctos
    public int comprobarCampos(){
    
        String mensaje = "";
        int valor = -3;
        
        if(comprobarCampoVacio(txtFieldNombre) | 
        comprobarCampoVacio(txtFieldApellido1) | 
        comprobarCampoVacio(txtFieldApellido2) | 
        comprobarCampoVacio(txtFieldEdad)){
            mensaje = "Algún campo esta sin completar.\nEs necesario rellenar todos los campos.";
            System.out.println(mensaje);
            valor = -1;
        }else if(!comprobarCampoVacio(txtFieldNombre) & 
        !comprobarCampoVacio(txtFieldApellido1) & 
        !comprobarCampoVacio(txtFieldApellido2) & 
        !comprobarCampoVacio(txtFieldEdad)){
            try{
                valor = 0;
            }catch(NumberFormatException e){
                mensaje = "La edad debe ser un número.";
                System.out.println(mensaje);
                valor = -2;
            }
        }
        
        return valor;
        
    }
    
    public void introducirPersona(){
    
        if(comprobarCampos()==0){
        
            int num = Integer.valueOf(txtFieldEdad.getText());
                String nombre = txtFieldNombre.getText();
                String apellido1 = txtFieldApellido1.getText();
                String apellido2 = txtFieldApellido2.getText();
            
            if(num > 0){
                Persona nuevaPersona = new Persona(nombre, apellido1, apellido2, num);
                manejador.addPerson(nuevaPersona, rutaTabla);
                if(vaciarCampos)
                    vaciarCampos();
                jTable1.setModel(new TableModel(rutaTabla));
            }else{
                System.out.println("La edad debe de ser mayor a 0");
            }
        
        }
        
    }
    
    public void eliminarPersona(){
    
        if(comprobarCampos()==0){
        
            int num = Integer.valueOf(txtFieldEdad.getText());
            String nombre = txtFieldNombre.getText();
            String apellido1 = txtFieldApellido1.getText();
            String apellido2 = txtFieldApellido2.getText();
            
            if(vaciarCampos)
                    vaciarCampos();

            Persona nuevaPersona = new Persona(nombre, apellido1, apellido2, num);
            manejador.deletePerson(nuevaPersona, rutaTabla);

            jTable1.setModel(new TableModel(rutaTabla));
        
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPersona = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtFieldNombre = new javax.swing.JTextField();
        txtFieldApellido1 = new javax.swing.JTextField();
        txtFieldApellido2 = new javax.swing.JTextField();
        txtFieldEdad = new javax.swing.JTextField();
        btnPersona = new javax.swing.JButton();
        comboBoxPersona = new javax.swing.JComboBox<>();
        checkBoxVaciarCampos = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemCargar = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuItemLimpiar = new javax.swing.JMenuItem();
        menuItemActualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new TableModel(new File("personas.txt")));
        tabla.setViewportView(jTable1);

        lblPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPersona.setText(" persona: ");

        lblNombre.setText("Nombre: ");

        lblApellido1.setText("Primer apellido: ");

        lblApellido2.setText("Segundo apellido:  ");

        lblEdad.setText("Edad: ");

        txtFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEdadActionPerformed(evt);
            }
        });

        btnPersona.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnPersona.setText("AGREGAR");
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });

        comboBoxPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboBoxPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar", "Eliminar", "Filtrar" }));
        comboBoxPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPersonaActionPerformed(evt);
            }
        });

        checkBoxVaciarCampos.setSelected(true);
        checkBoxVaciarCampos.setText("Vaciar campos");
        checkBoxVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxVaciarCamposActionPerformed(evt);
            }
        });

        menuArchivo.setText("Archivo...");

        menuItemCargar.setText("Cargar");
        menuItemCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCargarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemCargar);

        jMenuBar1.add(menuArchivo);

        menuEdicion.setText("Edición...");

        menuItemLimpiar.setText("Limpiar");
        menuItemLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLimpiarActionPerformed(evt);
            }
        });
        menuEdicion.add(menuItemLimpiar);

        menuItemActualizar.setText("Actualizar");
        menuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarActionPerformed(evt);
            }
        });
        menuEdicion.add(menuItemActualizar);

        jMenuBar1.add(menuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPersona))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFieldNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblApellido1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellido2)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnPersona)
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxVaciarCampos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersona)
                    .addComponent(comboBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad)
                    .addComponent(txtFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1)
                    .addComponent(txtFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido2)
                    .addComponent(txtFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersona)
                    .addComponent(checkBoxVaciarCampos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLimpiarActionPerformed
        try {
            manejador.vaciarArchivo(rutaTabla);
        } catch (IOException ex) {
            Logger.getLogger(FRAME_Tabla.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(new TableModel(rutaTabla));
    }//GEN-LAST:event_menuItemLimpiarActionPerformed

    private void txtFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEdadActionPerformed

    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        botonPersona(comboBoxPersona.getSelectedIndex());
    }//GEN-LAST:event_btnPersonaActionPerformed

    private void menuItemCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCargarActionPerformed
        escogerArchivo();
    }//GEN-LAST:event_menuItemCargarActionPerformed

    private void comboBoxPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPersonaActionPerformed
        cambiarTextoBoton(comboBoxPersona.getSelectedIndex());
    }//GEN-LAST:event_comboBoxPersonaActionPerformed

    private void menuItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarActionPerformed
        jTable1.setModel(new TableModel(rutaTabla));
    }//GEN-LAST:event_menuItemActualizarActionPerformed

    private void checkBoxVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxVaciarCamposActionPerformed
        vaciarCampos = checkBoxVaciarCampos.isSelected();
    }//GEN-LAST:event_checkBoxVaciarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void botonPersona(int valor){
    
        switch(valor) {
            case 0:
              introducirPersona();
              break;
            case 1:
              eliminarPersona();
              break;
            case 2:
              btnPersona.setText("FILTRAR");
              break;
            default:
        }
        
    }
    
    public void cambiarTextoBoton(int valor){
    
        switch(valor) {
            case 0:
              btnPersona.setText("AGREGAR");
              break;
            case 1:
              btnPersona.setText("ELIMINAR");
              break;
            case 2:
              btnPersona.setText("FILTRAR");
              break;
            default:
        }
        
    }
    
    public void escogerArchivo(){
        
        JFileChooser fileChooser = new JFileChooser(new File("personas.txt"));
        fileChooser.showOpenDialog(fileChooser);
        rutaTabla = new File(fileChooser.getSelectedFile().getAbsolutePath());
        jTable1.setModel(new TableModel(rutaTabla));
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME_Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersona;
    private javax.swing.JCheckBox checkBoxVaciarCampos;
    private javax.swing.JComboBox<String> comboBoxPersona;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuItemActualizar;
    private javax.swing.JMenuItem menuItemCargar;
    private javax.swing.JMenuItem menuItemLimpiar;
    private javax.swing.JScrollPane tabla;
    private javax.swing.JTextField txtFieldApellido1;
    private javax.swing.JTextField txtFieldApellido2;
    private javax.swing.JTextField txtFieldEdad;
    private javax.swing.JTextField txtFieldNombre;
    // End of variables declaration//GEN-END:variables
}
